import { Octokit } from '@octokit/rest';
import prisma from '../lib/prisma';
import { decryptToken } from '../utils/encryption';
import fs from 'fs';
import path from 'path';
import Handlebars from 'handlebars';

export class GitHubDeployer {
  private octokit: Octokit;

  constructor(encryptedToken: string) {
    const token = decryptToken(encryptedToken);
    this.octokit = new Octokit({ auth: token });
  }

  async deployPortfolio(userId: string, resumeId: string, repoName: string, templateId: string) {
    // 1. Fetch Resume & User Data
    const resume = await prisma.resume.findUnique({
      where: { id: resumeId, userId },
    });
    if (!resume) throw new Error('Resume not found');

    const user = await prisma.user.findUnique({
      where: { id: userId },
      select: { githubUsername: true },
    });
    if (!user || !user.githubUsername) throw new Error('GitHub not connected');

    // 2. Generate Portfolio locally via Handlebars
    let htmlContent: string;
    try {
      const templateDir = path.join(__dirname, '..', 'templates');
      // Use the provided templateId to load the corresponding HTML file (which now contains inline CSS)
      const templateFilename = `${templateId || 'portfolio-standard'}.html`;
      
      let indexTemplate;
      try {
        indexTemplate = fs.readFileSync(path.join(templateDir, templateFilename), 'utf-8');
      } catch (err) {
        // Fallback if the specific template file doesn't exist
        indexTemplate = fs.readFileSync(path.join(templateDir, 'portfolio-standard.html'), 'utf-8');
      }

      const compile = Handlebars.compile(indexTemplate);
      htmlContent = compile({ data: resume.parsedData });
    } catch (e: any) {
      console.error('[Handlebars Generate]', e.message);
      throw new Error('Failed to generate portfolio files locally');
    }

    // 3. Create or Get Repository
    let repo;
    try {
      const existingRepo = await this.octokit.rest.repos.get({
        owner: user.githubUsername,
        repo: repoName,
      });
      repo = existingRepo.data;
    } catch (e: any) {
      if (e.status === 404) {
        const newRepo = await this.octokit.rest.repos.createForAuthenticatedUser({
          name: repoName,
          description: 'My professional portfolio generated by NeatResume',
          auto_init: true,
          private: false,
        });
        repo = newRepo.data;
      } else {
        throw new Error('Failed to check repository status');
      }
    }

    // Wait for initial commit if newly created
    await new Promise(res => setTimeout(res, 2000));

    // 4. Get default branch SHA
    const branch = await this.octokit.rest.repos.getBranch({
      owner: user.githubUsername,
      repo: repoName,
      branch: repo.default_branch || 'main',
    });
    const baseTreeSha = branch.data.commit.commit.tree.sha;

    // 5. Create blobs
    const htmlBlob = await this.octokit.rest.git.createBlob({
        owner: user.githubUsername,
        repo: repoName,
        content: htmlContent,
        encoding: 'utf-8',
    });

    // 6. Create tree
    const tree = await this.octokit.rest.git.createTree({
      owner: user.githubUsername,
      repo: repoName,
      base_tree: baseTreeSha,
      tree: [
        { path: 'index.html', mode: '100644', type: 'blob', sha: htmlBlob.data.sha },
      ],
    });

    // 7. Create commit
    const commit = await this.octokit.rest.git.createCommit({
      owner: user.githubUsername,
      repo: repoName,
      message: 'Deploy portfolio updates via NeatResume',
      tree: tree.data.sha,
      parents: [branch.data.commit.sha],
    });

    // 8. Push
    await this.octokit.rest.git.updateRef({
      owner: user.githubUsername,
      repo: repoName,
      ref: `heads/${repo.default_branch || 'main'}`,
      sha: commit.data.sha,
    });

    // 9. Enable GitHub Pages
    const pagesUrl = `https://${user.githubUsername}.github.io/${repoName}/`;
    try {
      await this.octokit.rest.repos.createPagesSite({
        owner: user.githubUsername,
        repo: repoName,
        source: {
          branch: repo.default_branch || 'main',
          path: '/',
        },
      });
    } catch (e: any) {
      if (e.status !== 409) {
        console.warn('[GitHub Pages] Could not enable automatically:', e.message);
      }
    }

    // 10. Update Resume DB Status
    await prisma.resume.update({
      where: { id: resumeId },
      data: {
        portfolioUrl: pagesUrl,
        portfolioStatus: 'deployed',
        deployedAt: new Date(),
      },
    });

    return { success: true, url: pagesUrl };
  }
}
