import { Octokit } from '@octokit/rest';
import axios from 'axios';
import { PrismaClient } from '@prisma/client';
import { decryptToken } from '../utils/encryption';

const prisma = new PrismaClient();

export class GitHubDeployer {
  private octokit: Octokit;

  constructor(encryptedToken: string) {
    const token = decryptToken(encryptedToken);
    this.octokit = new Octokit({ auth: token });
  }

  async deployPortfolio(userId: string, resumeId: string, repoName: string) {
    // 1. Fetch Resume & User Data
    const resume = await prisma.resume.findUnique({
      where: { id: resumeId, userId }
    });
    if (!resume) throw new Error("Resume not found");

    const user = await prisma.user.findUnique({
      where: { id: userId }
    });
    if (!user || !user.githubUsername) throw new Error("GitHub not connected");

    // 2. Generate Portfolio via Python Service
    const PARSER_SERVICE_URL = (process.env.PARSER_SERVICE_URL || 'http://127.0.0.1:8000').replace(/\/$/, '');
    let generationResult;
    try {
      const response = await axios.post(`${PARSER_SERVICE_URL}/generate-portfolio`, resume.parsedData);
      generationResult = response.data;
    } catch (e: any) {
      console.error(e.response?.data || e.message);
      throw new Error("Failed to generate portfolio files from parser service");
    }

    const { 'index.html': htmlContent, 'styles.css': cssContent } = generationResult.files;

    // 3. Create or Get Repository
    let repo;
    try {
      const existingRepo = await this.octokit.rest.repos.get({
        owner: user.githubUsername,
        repo: repoName
      });
      repo = existingRepo.data;
    } catch (e: any) {
      if (e.status === 404) {
        // Create it
        const newRepo = await this.octokit.rest.repos.createForAuthenticatedUser({
          name: repoName,
          description: `My professional portfolio generated by NeatResume`,
          auto_init: true,
          private: false // Pages requires public repo for free tier
        });
        repo = newRepo.data;
      } else {
        throw new Error("Failed to check repository status");
      }
    }

    // Wait a brief moment if we just created the repo so the initial commit is available
    await new Promise(res => setTimeout(res, 2000));

    // 4. Get Default Branch Sha & Tree
    const branch = await this.octokit.rest.repos.getBranch({
      owner: user.githubUsername,
      repo: repoName,
      branch: repo.default_branch || 'main'
    });
    const baseTreeSha = branch.data.commit.commit.tree.sha;

    // 5. Create Blobs for files
    const htmlBlob = await this.octokit.rest.git.createBlob({
      owner: user.githubUsername,
      repo: repoName,
      content: htmlContent,
      encoding: 'utf-8'
    });
    
    const cssBlob = await this.octokit.rest.git.createBlob({
      owner: user.githubUsername,
      repo: repoName,
      content: cssContent,
      encoding: 'utf-8'
    });

    // 6. Create Tree
    const tree = await this.octokit.rest.git.createTree({
      owner: user.githubUsername,
      repo: repoName,
      base_tree: baseTreeSha,
      tree: [
        { path: 'index.html', mode: '100644', type: 'blob', sha: htmlBlob.data.sha },
        { path: 'styles.css', mode: '100644', type: 'blob', sha: cssBlob.data.sha }
      ]
    });

    // 7. Create Commit
    const commit = await this.octokit.rest.git.createCommit({
      owner: user.githubUsername,
      repo: repoName,
      message: 'Deploy portfolio updates via NeatResume',
      tree: tree.data.sha,
      parents: [branch.data.commit.sha]
    });

    // 8. Update Reference (push)
    await this.octokit.rest.git.updateRef({
      owner: user.githubUsername,
      repo: repoName,
      ref: `heads/${repo.default_branch || 'main'}`,
      sha: commit.data.sha
    });

    // 9. Enable or Configure GitHub Pages
    let pagesUrl = `https://${user.githubUsername}.github.io/${repoName}/`;
    try {
      await this.octokit.rest.repos.createPagesSite({
        owner: user.githubUsername,
        repo: repoName,
        source: {
          branch: repo.default_branch || 'main',
          path: '/'
        }
      });
    } catch (e: any) {
      if (e.status === 409 && e.message?.includes('already exists')) {
        // Ignored, that's fine
      } else {
        console.warn("Could not enable GitHub pages automatically:", e.message);
      }
    }

    // 10. Update Resume DB Status
    await prisma.resume.update({
      where: { id: resumeId },
      data: {
        portfolioUrl: pagesUrl,
        portfolioStatus: 'deployed',
        deployedAt: new Date()
      }
    });

    return {
      success: true,
      url: pagesUrl
    };
  }
}
